version: '3.3'

services:
  keycloak:
    image: pmasala/keycloak:octo-covid19
    hostname: keycloak
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: qwe123
      DB_VENDOR: h2
      PROXY_ADDRESS_FORWARDING: "true"